architecture-beta
    service client(internet)[Client]
    service nginx(logos:nginx)[Nginx port 80]
    service gunicorn(server)[Gunicorn port 8000]
    service worker1(logos:fastapi-icon)[Uvicorn Worker 1]
    service worker2(logos:fastapi-icon)[Uvicorn Worker 2]
    service mlflow(simple-icons:mlflow)[MLflow Registry]
    service artifacts(simple-icons:minio)[Model Artifacts]
    service logs(simple-icons:minio)[Prediction Logs]
    service prom(logos:prometheus)[Prometheus port 9090]

    client:R --> L:nginx
    nginx:R --> L:gunicorn
    gunicorn:R --> L:worker1
    gunicorn:B --> T:worker2
    worker1:R --> L:mlflow
    mlflow:R --> L:artifacts
    worker1:B --> T:logs
    worker1:B --> T:prom
